[package]
name = "polyanya"
version = "0.1.6"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["pathfinding"]
readme = "README.md"
description = "Polygon Any Angle Pathfinding"
repository = "https://github.com/vleue/polyanya"
homepage = "https://github.com/vleue/polyanya"
documentation = "https://docs.rs/polyanya"
categories = ["game-development"]

[features]
default = ["async"]
stats = []
verbose = []
async = []

[dependencies]
tracing = { version = "0.1", optional = true }
hashbrown = { version = "0.12" }
glam = { version = "0.21.3", features = ["approx"] }
smallvec = { version = "1.9", features = ["union", "const_generics"] }
bvh2d = "0.1"

[dev-dependencies]
criterion = "0.4"
tracing-tracy = "0.10"
tracing-subscriber = "0.3"
tracing = "0.1"

[lib]
bench = false

[[bench]]
name = "path"
harness = false

[[bench]]
name = "no_path"
harness = false

[[bench]]
name = "is_in_mesh"
harness = false

[[bench]]
name = "baking"
harness = false
